// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parakeet.Core.Attachments.Tables;
using Parakeet.Core.Database;
using Parakeet.Core.Spaces.Tables;
using Parakeet.Core.Users.Tables;

#nullable disable

namespace Parakeet.Core.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260701091333_baseMigration")]
    partial class baseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parakeet.Core.Accounts.Tables.Account", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deletion")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(105)
                        .HasColumnType("character varying(105)")
                        .HasColumnName("password");

                    b.HasKey("ID");

                    b.HasIndex("Deletion");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("Password");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Parakeet.Core.Auth.Tables.Invite", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimedBy");

                    b.Property<int>("RemainingUses")
                        .HasColumnType("integer")
                        .HasColumnName("remainingUses");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean")
                        .HasColumnName("valid");

                    b.HasKey("ID");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("Valid");

                    b.ToTable("invites");
                });

            modelBuilder.Entity("Parakeet.Core.Auth.Tables.Session", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userID");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("Token");

                    b.HasIndex("UserID");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Parakeet.Core.Spaces.Tables.Space", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Attachment>("Banner")
                        .HasColumnType("jsonb")
                        .HasColumnName("banner");

                    b.Property<List<Category>>("Categories")
                        .HasColumnType("jsonb")
                        .HasColumnName("categories");

                    b.PrimitiveCollection<List<string>>("Channels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("channels");

                    b.Property<long>("DefaultPerssions")
                        .HasColumnType("bigint")
                        .HasColumnName("default_permissions");

                    b.Property<Attachment>("Icon")
                        .HasColumnType("jsonb")
                        .HasColumnName("icon");

                    b.Property<bool>("IsNSFW")
                        .HasColumnType("boolean")
                        .HasColumnName("nsfw");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("uuid")
                        .HasColumnName("owner");

                    b.Property<Dictionary<string, Role>>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<string>("ServerDescription")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("description");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<SystemMessageChannels>("SystemMessages")
                        .HasColumnType("jsonb")
                        .HasColumnName("system_messages");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("OwnerID");

                    b.ToTable("spaces");
                });

            modelBuilder.Entity("Parakeet.Core.Users.Tables.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarID")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_id");

                    b.Property<int>("Badges")
                        .HasColumnType("integer")
                        .HasColumnName("badges");

                    b.Property<BotInformation>("Bot")
                        .HasColumnType("jsonb")
                        .HasColumnName("bot");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("discriminator");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<int>("Flags")
                        .HasColumnType("integer")
                        .HasColumnName("flags");

                    b.Property<DateTime>("LastAcknowledgedPolicyChange")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_acknowledged_policy_change");

                    b.Property<bool>("Privileged")
                        .HasColumnType("boolean")
                        .HasColumnName("privileged");

                    b.Property<UserProfile?>("Profile")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.PrimitiveCollection<List<string>>("Pronouns")
                        .HasColumnType("text[]")
                        .HasColumnName("pronouns");

                    b.Property<List<Relationship>>("Relationships")
                        .HasColumnType("jsonb")
                        .HasColumnName("relations");

                    b.Property<UserStatus?>("Status")
                        .HasColumnType("jsonb")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_until");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("username");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
